# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='team-solver-messages.proto',
  package='team_solver',
  serialized_pb='\n\x1ateam-solver-messages.proto\x12\x0bteam_solver\"\xb4\x02\n\x0e\x43ommandMessage\x12\r\n\x05\x63mdId\x18\x01 \x02(\x05\x12.\n\x04type\x18\x02 \x02(\x0e\x32 .team_solver.CommandMessage.Type\x12=\n\x08newQuery\x18\x03 \x01(\x0b\x32+.team_solver.CommandMessage.NewQueryMessage\x12\x43\n\x0b\x63\x61ncelQuery\x18\x04 \x01(\x0b\x32..team_solver.CommandMessage.CancelQueryMessage\x1a \n\x0fNewQueryMessage\x12\r\n\x05query\x18\x01 \x02(\t\x1a\x14\n\x12\x43\x61ncelQueryMessage\"\'\n\x04Type\x12\r\n\tNEW_QUERY\x10\x01\x12\x10\n\x0c\x43\x41NCEL_QUERY\x10\x02\"\xa6\x02\n\x0cReplyMessage\x12,\n\x04type\x18\x01 \x02(\x0e\x32\x1e.team_solver.ReplyMessage.Type\x12\r\n\x05\x63mdId\x18\x02 \x02(\x05\x12\r\n\x05stats\x18\x05 \x03(\t\x12\x36\n\x03sat\x18\x03 \x01(\x0b\x32).team_solver.ReplyMessage.SatReplyMessage\x12:\n\x05unsat\x18\x04 \x01(\x0b\x32+.team_solver.ReplyMessage.UnsatReplyMessage\x1a%\n\x0fSatReplyMessage\x12\x12\n\nassignment\x18\x01 \x02(\t\x1a\x13\n\x11UnsatReplyMessage\"\x1a\n\x04Type\x12\x07\n\x03SAT\x10\x01\x12\t\n\x05UNSAT\x10\x02')



_COMMANDMESSAGE_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='team_solver.CommandMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='NEW_QUERY', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CANCEL_QUERY', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=313,
  serialized_end=352,
)

_REPLYMESSAGE_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='team_solver.ReplyMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SAT', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UNSAT', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=623,
  serialized_end=649,
)


_COMMANDMESSAGE_NEWQUERYMESSAGE = descriptor.Descriptor(
  name='NewQueryMessage',
  full_name='team_solver.CommandMessage.NewQueryMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='query', full_name='team_solver.CommandMessage.NewQueryMessage.query', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=257,
  serialized_end=289,
)

_COMMANDMESSAGE_CANCELQUERYMESSAGE = descriptor.Descriptor(
  name='CancelQueryMessage',
  full_name='team_solver.CommandMessage.CancelQueryMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=291,
  serialized_end=311,
)

_COMMANDMESSAGE = descriptor.Descriptor(
  name='CommandMessage',
  full_name='team_solver.CommandMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cmdId', full_name='team_solver.CommandMessage.cmdId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='team_solver.CommandMessage.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='newQuery', full_name='team_solver.CommandMessage.newQuery', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cancelQuery', full_name='team_solver.CommandMessage.cancelQuery', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_COMMANDMESSAGE_NEWQUERYMESSAGE, _COMMANDMESSAGE_CANCELQUERYMESSAGE, ],
  enum_types=[
    _COMMANDMESSAGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=44,
  serialized_end=352,
)


_REPLYMESSAGE_SATREPLYMESSAGE = descriptor.Descriptor(
  name='SatReplyMessage',
  full_name='team_solver.ReplyMessage.SatReplyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='assignment', full_name='team_solver.ReplyMessage.SatReplyMessage.assignment', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=563,
  serialized_end=600,
)

_REPLYMESSAGE_UNSATREPLYMESSAGE = descriptor.Descriptor(
  name='UnsatReplyMessage',
  full_name='team_solver.ReplyMessage.UnsatReplyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=602,
  serialized_end=621,
)

_REPLYMESSAGE = descriptor.Descriptor(
  name='ReplyMessage',
  full_name='team_solver.ReplyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='team_solver.ReplyMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cmdId', full_name='team_solver.ReplyMessage.cmdId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stats', full_name='team_solver.ReplyMessage.stats', index=2,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sat', full_name='team_solver.ReplyMessage.sat', index=3,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='unsat', full_name='team_solver.ReplyMessage.unsat', index=4,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REPLYMESSAGE_SATREPLYMESSAGE, _REPLYMESSAGE_UNSATREPLYMESSAGE, ],
  enum_types=[
    _REPLYMESSAGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=355,
  serialized_end=649,
)


_COMMANDMESSAGE_NEWQUERYMESSAGE.containing_type = _COMMANDMESSAGE;
_COMMANDMESSAGE_CANCELQUERYMESSAGE.containing_type = _COMMANDMESSAGE;
_COMMANDMESSAGE.fields_by_name['type'].enum_type = _COMMANDMESSAGE_TYPE
_COMMANDMESSAGE.fields_by_name['newQuery'].message_type = _COMMANDMESSAGE_NEWQUERYMESSAGE
_COMMANDMESSAGE.fields_by_name['cancelQuery'].message_type = _COMMANDMESSAGE_CANCELQUERYMESSAGE
_COMMANDMESSAGE_TYPE.containing_type = _COMMANDMESSAGE;
_REPLYMESSAGE_SATREPLYMESSAGE.containing_type = _REPLYMESSAGE;
_REPLYMESSAGE_UNSATREPLYMESSAGE.containing_type = _REPLYMESSAGE;
_REPLYMESSAGE.fields_by_name['type'].enum_type = _REPLYMESSAGE_TYPE
_REPLYMESSAGE.fields_by_name['sat'].message_type = _REPLYMESSAGE_SATREPLYMESSAGE
_REPLYMESSAGE.fields_by_name['unsat'].message_type = _REPLYMESSAGE_UNSATREPLYMESSAGE
_REPLYMESSAGE_TYPE.containing_type = _REPLYMESSAGE;

class CommandMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class NewQueryMessage(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _COMMANDMESSAGE_NEWQUERYMESSAGE
    
    # @@protoc_insertion_point(class_scope:team_solver.CommandMessage.NewQueryMessage)
  
  class CancelQueryMessage(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _COMMANDMESSAGE_CANCELQUERYMESSAGE
    
    # @@protoc_insertion_point(class_scope:team_solver.CommandMessage.CancelQueryMessage)
  DESCRIPTOR = _COMMANDMESSAGE
  
  # @@protoc_insertion_point(class_scope:team_solver.CommandMessage)

class ReplyMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class SatReplyMessage(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REPLYMESSAGE_SATREPLYMESSAGE
    
    # @@protoc_insertion_point(class_scope:team_solver.ReplyMessage.SatReplyMessage)
  
  class UnsatReplyMessage(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REPLYMESSAGE_UNSATREPLYMESSAGE
    
    # @@protoc_insertion_point(class_scope:team_solver.ReplyMessage.UnsatReplyMessage)
  DESCRIPTOR = _REPLYMESSAGE
  
  # @@protoc_insertion_point(class_scope:team_solver.ReplyMessage)

# @@protoc_insertion_point(module_scope)
